Update Jenkinsfile

diff --git a/CICD/Jenkinsfile b/CICD/Jenkinsfile
--- a/CICD/Jenkinsfile
+++ b/CICD/Jenkinsfile
@@ -7,31 +7,58 @@ pipeline {
         BACKEND_STORE_URI = credentials('backend-store-uri') // Credential Backend Store URI
         ARTIFACT_STORE_URI = credentials('artifact-store-uri') // Credential Artifact Store URI
         POSTMARK_API_KEY = credentials('postmark-api-key') // Credential Postmark API Key
-        MLFLOW_EXPERIMENT_NAME = credentials('mlflow-experiment-name') // Credential pour le nom de l'expérience
+        MLFLOW_EXPERIMENT_NAME = credentials('mlflow-experiment-name') // Nouvelle variable ajoutée
     }
     stages {
         stage('Checkout') {
             steps {
-                // Cloner le dépôt GitHub
+                // Cloner le code source depuis GitHub
                 checkout scm
             }
         }
 
-        stage('Build Docker Image') {
+        stage('Build Docker Images') {
             steps {
-                dir('CICD/mlflow') {
-                    sh """
-                    docker build -t mlflow-image --build-arg REPO_URL=https://github.com/username/project-name.git .
-                    """
+                parallel (
+                    "Build MLflow Image": {
+                        dir('CICD/mlflow') {
+                            sh 'docker build -t mlflow-image .'
+                        }
+                    },
+                    "Build API Image": {
+                        dir('CICD/API') {
+                            sh 'docker build -t fraud-detection-api .'
+                        }
+                    }
+                )
+            }
+        }
+
+        stage('Generate .env File') {
+            steps {
+                dir('CICD') {
+                    script {
+                        writeFile file: '.env', text: """
+APP_URI=${APP_URI}
+AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
+AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
+BACKEND_STORE_URI=${BACKEND_STORE_URI}
+ARTIFACT_STORE_URI=${ARTIFACT_STORE_URI}
+POSTMARK_API_KEY=${POSTMARK_API_KEY}
+MLFLOW_EXPERIMENT_NAME=${MLFLOW_EXPERIMENT_NAME}
+"""
+                    }
+                    // Afficher le contenu pour vérification (supprimez cette ligne en production)
+                    sh 'cat .env'
                 }
             }
         }
 
         stage('Run Training Script') {
             steps {
-                script {
+                dir('CICD/mlflow') {
                     sh """
-                    docker run --env-file CICD/.env -p 4000:4000 mlflow-image python /home/app/CICD/mlflow/train.py
+                    docker run --env-file ../.env -p 4000:4000 -v "\$(pwd):/home/app" mlflow-image python /home/app/train.py
                     """
                 }
             }
@@ -39,23 +66,25 @@ pipeline {
 
         stage('Run Tests') {
             steps {
-                script {
-                    def test_result = sh(script: """
-                    docker run --env-file CICD/.env \
-                        mlflow-image \
-                        pytest --maxfail=1 --disable-warnings -q /home/app/CICD/tests
-                    """, returnStatus: true)
+                dir('CICD') {
+                    script {
+                        def test_result = sh(script: """
+                        docker run --env-file .env \
+                            -v "\$(pwd)/tests:/home/app/tests" mlflow-image \
+                            pytest --maxfail=1 --disable-warnings -q /home/app/tests/test_data_preprocessing.py /home/app/tests/test_model_training.py
+                        """, returnStatus: true)
 
-                    if (test_result != 0) {
-                        echo "Tests failed. Sending alert email..."
-                        sh """
-                        docker run --env-file CICD/.env \
-                            mlflow-image \
-                            python /home/app/CICD/mlflow/send_email.py "Tests Failed" "Les tests ont échoué. Vérifiez les logs Jenkins."
-                        """
-                        error "Tests failed. Pipeline stopped."
-                    } else {
-                        echo "All tests passed successfully."
+                        if (test_result != 0) {
+                            echo "Tests failed. Sending alert email..."
+                            sh """
+                            python3 mlflow/send_email.py \
+                                "Tests échoués" \
+                                "Un ou plusieurs tests ont échoué. Veuillez vérifier les logs Jenkins pour plus de détails."
+                            """
+                            error "Tests failed. Pipeline stopped."
+                        } else {
+                            echo "All tests passed successfully."
+                        }
                     }
                 }
             }
@@ -63,18 +92,20 @@ pipeline {
 
         stage('Validate Model Performance') {
             steps {
-                script {
-                    def validation_passed = sh(script: """
-                    docker run --env-file CICD/.env \
-                        mlflow-image \
-                        python /home/app/CICD/mlflow/check_model_performance.py
-                    """, returnStatus: true)
+                dir('CICD/mlflow') {
+                    script {
+                        def validation_passed = sh(script: """
+                        docker run --env-file ../.env \
+                            -v "\$(pwd):/home/app" mlflow-image \
+                            python /home/app/check_model_performance.py
+                        """, returnStatus: true)
 
-                    if (validation_passed != 0) {
-                        echo "Validation failed. Model does not meet performance criteria."
-                        currentBuild.result = "UNSTABLE"
-                    } else {
-                        echo "Validation passed. Model meets performance criteria."
+                        if (validation_passed != 0) {
+                            echo "Validation failed. Model does not meet performance criteria."
+                            currentBuild.result = "UNSTABLE" // Marque la build comme instable
+                        } else {
+                            echo "Validation passed. Model meets performance criteria."
+                        }
                     }
                 }
             }
@@ -85,35 +116,57 @@ pipeline {
                 expression { currentBuild.result == "UNSTABLE" }
             }
             steps {
-                sh """
-                docker run --env-file CICD/.env \
-                    mlflow-image \
-                    python /home/app/CICD/mlflow/rollback_model.py
-                """
+                dir('CICD/mlflow') {
+                    sh """
+                    docker run --env-file ../.env \
+                        -v "\$(pwd):/home/app" mlflow-image \
+                        python /home/app/rollback_model.py
+                    """
+                }
             }
         }
 
-        stage('Run API Container') {
+        stage('Deploy API') {
             steps {
-                sh """
-                docker rm -f fraud-detection-api || true
-                docker run -d -p 8005:8005 --name fraud-detection-api mlflow-image
-                """
+                dir('CICD/API') {
+                    sh """
+                    docker run --network host -d \
+                        -v "\$(pwd):/home/app" \
+                        fraud-detection-api \
+                        python /home/app/api.py
+                    """
+                }
             }
         }
+        stage('Post-build Cleanup') {
+            steps {
+                echo "Cleaning up Docker containers and images..."
+                sh '''
+                # Supprimer tous les conteneurs utilisant les images mlflow-image et fraud-detection-api
+                docker ps -a --filter "ancestor=mlflow-image" -q | xargs -r docker rm -f
+                docker ps -a --filter "ancestor=fraud-detection-api" -q | xargs -r docker rm -f
+
+                # Supprimer les images Docker
+                docker rmi --force mlflow-image fraud-detection-api || true
+        '''
+            }
+        }
+
     }
 
     post {
         always {
-            echo "Pipeline terminé. Vérifiez l'état des étapes."
+            echo "Pipeline terminé. Vérifiez l'état des tests et des étapes précédentes."
         }
         failure {
             echo "Une erreur est survenue. Envoi d'un email d'alerte..."
-            sh """
-            docker run --env-file CICD/.env \
-                mlflow-image \
-                python /home/app/CICD/mlflow/send_email.py "Pipeline Jenkins Failed" "Une erreur est survenue. Vérifiez les logs Jenkins."
-            """
+            dir('CICD/mlflow') {
+                sh """
+                python3 send_email.py \
+                    "Pipeline Jenkins Échoué" \
+                    "Le pipeline Jenkins a échoué dans une des étapes. Veuillez vérifier les logs pour plus de détails."
+                """
+            }
         }
     }
 }
